from animal import Animal
from operations import Operations

# Weight loss
DOG_LOSS_WEIGHT_MULTIPLIER = 64
CAT_LOSS_WEIGHT_MULTIPLIER = 85

DOG_LOSS_WEIGHT_EXPOENT = 0.75
CAT_LOSS_WEIGHT_EXPOENT = 0.4

RESTING_DOG_WEIGHT_MAINTANCE_KCAL = 70 
INACTIVE_DOG_WEIGHT_MAINTANCE_KCAL = 95
ACTIVE_DOG_WEIGHT_MAINTANCE_KCAL = 130

# Weight maintance
RESTING_DOG_WEIGHT_MAINTANCE_EXPOENT = 0.75 
INACTIVE_DOG_WEIGHT_MAINTANCE_EXPOENT = 0.75
ACTIVE_DOG_WEIGHT_MAINTANCE_EXPOENT = 0.75


SLIM_CAT_WEIGHT_MAINTANCE_KCAL = 63.5
ACTIVE_CAT_WEIGHT_MAINTANCE_KCAL = 100
OBESE_CAT_WEIGHT_MAINTANCE_KCAL = 130

SLIM_CAT_WEIGHT_MAINTANCE_KCAL = 0.57
ACTIVE_CAT_WEIGHT_MAINTANCE_KCAL = 0.57
OBESE_CAT_WEIGHT_MAINTANCE_KCAL = 0.4


# Menu constants
TITLE_MAIN = "Calculadora de Necessidade Energética\n"
TITLE_ANIMAL_SELECT = "Selecione o Animal:\n"
TITLE_SELECT_ANIMAL_WEIGHT = "\n[?] Qual o peso corporal do animal? "
TITLE_LOOP = "[?] Calcular novamente? (aperte ENTER para SIM)\n"

MENU_OPTIONS = [Operations.WEIGHT_MAINTENANCE.to_string(), Operations.WEIGHT_REDUCE.to_string(), Operations.WEIGHT_GAIN.to_string()]
ANIMALS = [Animal.CAT, Animal.DOG]
